# Chassis Configuration
#
# See: http://docs.chassis.io/en/latest/config/

hosts:
    - wp-id.local

apt_mirror: Yes

php: 7.0

extensions:
  - Chassis/nodejs
  - Chassis/Composer
  - Chassis/Fish
  - Chassis/Xdebug
